export const CREATEPROJECT_INPUTS = "CREATEPROJECT_INPUTS";

export const SUCCESS_MSG = "SUCCESS_MSG";

export const GETALL_PROJECTS = "GETALL_PROJECTS";

export const DELETE_PROJECT = "DELETE_PROJECT";

export const DELETE_PROJECT_INPUTS = "DELETE_PROJECT_INPUTS";

export const EDIT_PROJECT_INPUTS = "EDIT_PROJECT_INPUTS";


